"""create tables

Revision ID: f3966ef20794
Revises: 
Create Date: 2026-03-13 12:54:04.032952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3966ef20794'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ptid', sa.Integer(), nullable=False),
    sa.Column('load', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ptid', sa.Integer(), nullable=False),
    sa.Column('lbmp', sa.Float(), nullable=False),
    sa.Column('marg_cost_loss', sa.Float(), nullable=False),
    sa.Column('marg_cost_congestion', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('load')
    # ### end Alembic commands ###
